apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-node
  name: my-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-node
    spec:
      containers:
      - image: 445567110488.dkr.ecr.us-east-1.amazonaws.com/my-cicd-app:latest
        name: my-cicd-app-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: my-node
spec:
  selector:
      app: my-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
